### ISSUE TITLE
Case-Insensitive Search in 'cd' Mode, or even Fuzzy-Find Mode

### ISSUE THREAD

**Issue by DrTobe** [dsxmachina/rfm#2]
It would be nice if the `cd` mode filename-matching would be case-insensitive or even fuzzy.

**Comment by dsxmachina** [comment]
Hmm, I don't really like fuzzy matching when it comes to changing directories. The 'cd' feature is written in a way, that e.g. it automatically jumps into the next directory, if your input only matches a character in the child-directory but not in the parent-directory.

This would be completely gone, if we would use a fuzzy search here.

But have you tried the "find" feature (if you hit "f") ?
 To be honest, I mostly use this, when I want to switch directories, because it automatically hides all non-matching directories.
This uses a case-insensitive matching of substrings (which is way more relaxed). I could imagine using a similar mechanism in the "cd" case

**Comment by DrTobe** [comment]
Both `cd` and `f` feel little intuitive to me. I will check out the different possibilities again as soon as I _find_ some time.

**Comment by dsxmachina** [comment]
It may be because I use the cd feature everyday, or because it am used to this style (as it is the exact behaviour that emacs dired has), but I decided to keep it that way; which is why I will close this issue now.
